# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Check Manifests

on:
  push:
    branches: [main, dev, 1.0*, 2.0*, fasttrack/*]
  pull_request:
    branches: [main, dev, 1.0*, 2.0*, fasttrack/*]

jobs:
  build:
    name: Check Manifests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Check x86_64 manifests
      run: |
        pushd toolkit
        make check-x86_64-manifests
        popd

    - name: Check aarch64 manifests
      run: |
        pushd toolkit
        make check-aarch64-manifests
        popd
      if: always()
